version: '3'

services:
  electronic-shop:
    build:
      context: .
      dockerfile: ./electronic-shop/Dockerfile  
    mem_limit: 1000m
    ports:
      - "8080:8080"
    environment:
      USER_ADMIN: postgres
      PASSWORD_ADMIN: Jose47847263#
      DATABASE_URL: jdbc:postgresql://tuch_store:5432/tuchStore?createDatabaseIfNotExist=true&serverTimezone=UTC
      SECRET_KEY: 64e7311cec505f980dd376d096c211bbc0cc63e902836c23acdbe82bc889536d
      MP_ACCESS_TOKEN: APP_USR-1298906713312457-012517-66477ece64338fa5dc3ee131124e0a6d-2230808817
      CLIENT_ID: 1298906713312457
      CLIENT_SECRET: hAYSJr0BJFsXAIKvroS4y28bW1DsNMsD
    restart: always

  tuch_store:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jose47847263#
      POSTGRES_DB: tuchStore
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "tuchStore"]
      interval: 10s
      retries: 5
      timeout: 5s
